name: vyapaar_connect
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.0
  image_picker: ^1.0.7
  http: ^1.2.0
  google_mlkit_text_recognition: ^0.13.0


flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/illustrations/
